### ISSUE TITLE
Where can I download the 3D version of the label files?

### ISSUE THREAD

**Issue by yangzhi-psy** [ntustison/antsCookTemplatePriorsExample#1]
Dear Nick,
1) Where can I download the 3D version of the label files? (in the folder DataForTemplateLabeling)
2) I'm trying to generate prior files for my own template for children. What is a proper starting point for tissue priors?

**Comment by ntustison** [comment]
> 1. Where can I download the 3D version of the label files? (in the folder DataForTemplateLabeling)

Look in this [directory](https://drive.google.com/drive/folders/0B4SvObeEfaRyZGhlUlJOcmItTVU?usp=sharing) specifically in the ``training_labels`` (``*6Labels.nii.gz``) and ``training_images`` subfolders.  

> 2. I'm trying to generate prior files for my own template for children. What is a proper starting point for tissue priors?

Similar as the adult case.  Here's the [NKI < 10](https://drive.google.com/drive/folders/0B4SvObeEfaRyamJSOGJvQnRLa1U?usp=sharing) data set.
