### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zhaolei215** [ntustison/antsCookTemplatePriorsExample#2]
Hello, could you please tell me how to obtain the labels file in the DataForTemplateLabeling folder

**Comment by ntustison** [comment]
If you're looking for the names of the labels in the images, I don't have one.

**Comment by zhaolei215** [comment]
I would like to know how to create labels similar to those in your CT image in MRI image

**Comment by ntustison** [comment]
You can use something like http://www.itksnap.org to draw your own labels.

**Comment by zhaolei215** [comment]
Thank you very much for your reply. As I am not a medical student, I am not sure which part of the brain it is. Is it gray matter? One more question, have you ever done priors based on MRI templates?
